name: Auto Create Secrets

on:
  push:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create secrets file
      run: |
        mkdir -p .streamlit
        echo "API_KEY = '${{ secrets.APP_API_KEY }}'" > .streamlit/secrets.toml
