name: Test Tools Functions

on:
  workflow_dispatch: # Cho phép nhấn nút chạy thủ công trên GitHub Actions

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas joblib scikit-learn

      - name: Run Test tools.py
        run: |
          python tools.py
