name: Train Machine Learning Model

on:
  workflow_dispatch: # Cho phép nhấn nút bấm chạy thủ công trên GitHub

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn joblib

      - name: Run Machine Learning Training
        run: python ml_model.py

      - name: Commit and Push trained model back to repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.name "github-actions[bot]@users.noreply.github.com"
          git add admission_model.pkl
          git commit -m "Auto train and update ML model" || exit 0
          git push
      - name: Commit and push trained model
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add score_predictor_model.pkl
          git commit -m "Auto update trained model [skip ci]" || exit 0
          git push
